SELECT * FROM PIZZA_SALES;

-- 1. TOTAL REVENUE.
SELECT SUM(TOTAL_PRICE) AS TOTAL_REVENUE
FROM 
PIZZA_SALES;

-- 2. AVERAGE ORDER VALUE MEANING AVERAGE AMOUNT SPENT PER ORDER WHICH IS CALCULATED BY DIVIDING THE TOTAL REVENUE
-- BY THE TOTAL NUMBER OF ORDERS.

SELECT ROUND(SUM(TOTAL_PRICE) / COUNT(DISTINCT ORDER_ID), 2) AS AVG_ORDER_VALUE
FROM PIZZA_SALES;

-- 3. TOTAL PIZZAS SOLD.

SELECT SUM(QUANTITY) AS TOTAL_PIZZAS_SOLD
FROM 
PIZZA_SALES;

-- 4. TOTAL ORDERS PLACED.

SELECT COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM 
PIZZA_SALES;

-- 5. AVERAGE PIZZAS PER ORDER.

SELECT CAST(CAST(SUM(QUANTITY) AS DECIMAL(10,2)) / CAST(COUNT(DISTINCT ORDER_ID) AS DECIMAL(10,2)) AS
DECIMAL (10,2)) AS AVERAGE_PIZZAS_PER_ORDER
FROM 
PIZZA_SALES;

-- 6. DAILY TREND FOR TOTAL ORDERS.

SELECT TO_CHAR(order_date, 'Day') AS order_day, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_SALES
GROUP BY TO_CHAR(ORDER_DATE, 'Day')
ORDER BY MIN(EXTRACT(DOW FROM ORDER_DATE));

-- 7. HOURLY TREND FOR TOTAL ORDERS.

SELECT EXTRACT(HOUR FROM ORDER_TIME) AS HOURLY_TIME, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM PIZZA_SALES
GROUP BY EXTRACT(HOUR FROM ORDER_TIME)
ORDER BY HOURLY_TIME;

-- 8. PERCENTAGE OF SALES BY PIZZA CATEGORY.

SELECT 
    PIZZA_CATEGORY, 
    SUM(TOTAL_PRICE) AS TOTAL_SALES, 
    SUM(TOTAL_PRICE) * 100 / (SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALES WHERE EXTRACT(MONTH FROM ORDER_DATE) = 1) AS PCT
FROM PIZZA_SALES
WHERE EXTRACT(MONTH FROM ORDER_DATE) = 1
GROUP BY PIZZA_CATEGORY;

-- 9. PERCENTAGE OF SALES BY PIZZA SIZE.

SELECT 
    PIZZA_SIZE, 
    CAST(SUM(TOTAL_PRICE) AS DECIMAL(10,2)) AS TOTAL_SALES, 
    CAST(SUM(TOTAL_PRICE) * 100 / (SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALES) AS DECIMAL(10,2)) AS PCT
FROM PIZZA_SALES
GROUP BY PIZZA_SIZE
ORDER BY PCT DESC;

-- 10. TOTAL PIZZAS SOLD BY PIZZA CATEGORY.

SELECT PIZZA_CATEGORY, SUM(QUANTITY) AS TOTAL_PIZZAS_SOLD
FROM PIZZA_SALES
GROUP BY PIZZA_CATEGORY
ORDER BY TOTAL_PIZZAS_SOLD ASC

-- 11. TOP 5 BEST SELLERS BY TOTAL PIZZAS SOLD.

SELECT PIZZA_NAME,
SUM(QUANTITY) AS TOTAL_PIZZAS_SOLD
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_PIZZAS_SOLD DESC LIMIT 5;

-- 12. BOTTOM 5 WORST SELLERS BY TOTAL PIZZAS SOLD.

SELECT PIZZA_NAME,
SUM(QUANTITY) AS TOTAL_PIZZAS_SOLD
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_PIZZAS_SOLD ASC LIMIT 5;




